name: Publish
on:
  push:
    branches:
    - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
      run: |
        VERSION=$(node bin/aspublish.js --version)
        if [ -z "$VERSION" ]; then
          echo "Changes do not trigger a release"
        else
          echo "Publishing new version: $VERSION"
          node bin/aspublish.js
        fi
